### ISSUE TITLE
GNU GPL v3 violation

### ISSUE THREAD

**Issue by simonSlamka** [GhostyORG/RPG_Discord_Bot#67]
Hello,

In the description of this repo, you say that anybody who uses this repo and subsequently releases their bot will have action taken against it.
The GPL v3 license allows for both noncommercial and commercial use, as long as a copyright notice is included and the same license is used. The source of the work used has to be cited as well, but that's it. They are free to use it. You explicitly chose the GPL v3 license when creating the repo, therefore people are free to do what the license allows them to do. Please, either remove the threat from the description or change the license.

Thank you

**Comment by virtual-designer** [comment]
Yup @killerclaws12 you should be aware of it

**Comment by killerclaws12** [comment]
> Hello,
> 
> In the description of this repo, you say that anybody who uses this repo and subsequently releases their bot will have action taken against it. The GPL v3 license allows for both noncommercial and commercial use, as long as a copyright notice is included and the same license is used. The source of the work used has to be cited as well, but that's it. They are free to use it. You explicitly chose the GPL v3 license when creating the repo, therefore people are free to do what the license allows them to do. Please, either remove the threat from the description or change the license.
> 
> Thank you

Bare with me here. High functioning autism and don't know how to word stuff properly. I meant like if they upload the bot to another repo and claim it as theirs.

**Comment by simonSlamka** [comment]
> > Hello,
> > In the description of this repo, you say that anybody who uses this repo and subsequently releases their bot will have action taken against it. The GPL v3 license allows for both noncommercial and commercial use, as long as a copyright notice is included and the same license is used. The source of the work used has to be cited as well, but that's it. They are free to use it. You explicitly chose the GPL v3 license when creating the repo, therefore people are free to do what the license allows them to do. Please, either remove the threat from the description or change the license.
> > Thank you
> 
> Bare with me here. High functioning autism and don't know how to word stuff properly. I meant like if they upload the bot to another repo and claim it as theirs.

Doesn't excuse anything. Like I said, you should either remove the threat or change your repo's license.
